### ISSUE TITLE
all python script in examples Folder Fatal Python error

### ISSUE THREAD

**Issue by cn0xroot** [BastilleResearch/gr-nordic#3]
nice to talk to you， when execute you python script get the error message:

```

./nordic_sniffer_scanner.py 
Mac OS; Clang version 7.3.0 (clang-703.0.31); Boost_105900; UHD_003.010.000.000-MacPorts-Release

Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

```
python nordic_receiver.py --channel 4 --data_rate 2e6 --crc_length 2 --address_length 5 --samples_per_symbol 2 --gain 40
Traceback (most recent call last):
  File "nordic_receiver.py", line 6, in <module>
    import nordic
ImportError: No module named nordic
```

how to fix it?thx!

**Comment by marcnewlin** [comment]
@cn0xroot, I hope all is well :) 

My guess is there was a problem during the make/install process. Do you have `swig` on your machine? If this is missing, the install process will appear to complete successfully, but this error is produced. 

Let me know if installing `swig` doesn't fix it!

**Comment by cn0xroot** [comment]
swig has been install 

but when i make/install twice again, it doesn't fix.

this is complete info:

```
sudo brew install swig
Password:
Warning: swig-3.0.7 already installed
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

```
ls /usr/local/lib/python2.7/site-packages/osmosdr/
__init__.py             _osmosdr_swig.so        osmocom_siggen_base.pyo osmosdr_swig.pyo
__init__.pyc            osmocom_siggen_base.py  osmosdr_swig.py
__init__.pyo            osmocom_siggen_base.pyc osmosdr_swig.pyc
```

```
mkdir build
cd build/
cmake ../
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- The C compiler identification is AppleClang 7.3.0.7030031
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cppunit'
--   Found cppunit, version 1.13.2
-- Found CPPUNIT: /opt/local/lib/libcppunit.dylib  
-- Found Doxygen: /opt/local/bin/doxygen (found version "1.8.10") 
Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.10.1
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib
-- Found GNURADIO_RUNTIME: /opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib  
GNURADIO_RUNTIME_FOUND = TRUE
CMake Warning (dev) at /opt/local/share/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "test-nordic".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  lib/CMakeLists.txt:80 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.10.
-- Found SWIG: /opt/local/bin/swig  
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2") 
-- Found PythonInterp: /usr/local/bin/python2 (found suitable version "2.7.10", minimum required is "2") 
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Failed
-- Configuring done
-- Generating done
-- Build files have been written 
```

```
make
Scanning dependencies of target gnuradio-nordic
[  3%] Building CXX object lib/CMakeFiles/gnuradio-nordic.dir/nordic_rx_impl.cc.o
[  7%] Building CXX object lib/CMakeFiles/gnuradio-nordic.dir/bit_shifting_byte_vector.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-nordic.dir/nordic_tx_impl.cc.o
[ 14%] Building CXX object lib/CMakeFiles/gnuradio-nordic.dir/enhanced_shockburst_packet.cc.o
[ 18%] Linking CXX shared library libgnuradio-nordic.dylib
[ 18%] Built target gnuradio-nordic
Scanning dependencies of target test-nordic
[ 22%] Building CXX object lib/CMakeFiles/test-nordic.dir/test_nordic.cc.o
[ 25%] Building CXX object lib/CMakeFiles/test-nordic.dir/qa_nordic.cc.o
[ 29%] Linking CXX executable test-nordic
[ 29%] Built target test-nordic
Scanning dependencies of target _nordic_swig_doc_tag
[ 33%] Building CXX object swig/CMakeFiles/_nordic_swig_doc_tag.dir/_nordic_swig_doc_tag.cpp.o
[ 37%] Linking CXX executable _nordic_swig_doc_tag
[ 37%] Built target _nordic_swig_doc_tag
Scanning dependencies of target nordic_swig_swig_doc
[ 40%] Generating doxygen xml for nordic_swig_doc docs
warning: Tag `XML_SCHEMA' at line 1478 of file `/Users/Good-Soon/gr-nordic/examples/gr-nordic/build/swig/nordic_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 1484 of file `/Users/Good-Soon/gr-nordic/examples/gr-nordic/build/swig/nordic_swig_doc_swig_docs/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[ 44%] Generating python docstrings for nordic_swig_doc
[ 44%] Built target nordic_swig_swig_doc
Scanning dependencies of target _nordic_swig_swig_tag
[ 48%] Building CXX object swig/CMakeFiles/_nordic_swig_swig_tag.dir/_nordic_swig_swig_tag.cpp.o
[ 51%] Linking CXX executable _nordic_swig_swig_tag
[ 51%] Built target _nordic_swig_swig_tag
[ 55%] Generating nordic_swig.tag
Scanning dependencies of target nordic_swig_swig_2d0df
[ 59%] Building CXX object swig/CMakeFiles/nordic_swig_swig_2d0df.dir/nordic_swig_swig_2d0df.cpp.o
[ 62%] Linking CXX executable nordic_swig_swig_2d0df
Swig source
[ 62%] Built target nordic_swig_swig_2d0df
Scanning dependencies of target pygen_swig_2a55b
[ 66%] Generating nordic_swig.pyc
[ 70%] Generating nordic_swig.pyo
[ 74%] Built target pygen_swig_2a55b
Scanning dependencies of target _nordic_swig
[ 77%] Building CXX object swig/CMakeFiles/_nordic_swig.dir/nordic_swigPYTHON_wrap.cxx.o
[ 81%] Linking CXX shared module _nordic_swig.so
[ 88%] Built target _nordic_swig
Scanning dependencies of target pygen_python_7499f
[ 92%] Generating __init__.pyc
[ 96%] Generating __init__.pyo
[ 96%] Built target pygen_python_7499f
Scanning dependencies of target pygen_apps_9a6dd
[ 96%] Built target pygen_apps_9a6dd
Scanning dependencies of target doxygen_target
[100%] Generating documentation with doxygen
warning: Tag `XML_SCHEMA' at line 1510 of file `/Users/Good-Soon/gr-nordic/examples/gr-nordic/build/docs/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 1516 of file `/Users/Good-Soon/gr-nordic/examples/gr-nordic/build/docs/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[100%] Built target doxygen_target
```

```
sudo make  install
Password:
[ 18%] Built target gnuradio-nordic
[ 29%] Built target test-nordic
[ 37%] Built target _nordic_swig_doc_tag
[ 44%] Built target nordic_swig_swig_doc
[ 51%] Built target _nordic_swig_swig_tag
[ 62%] Built target nordic_swig_swig_2d0df
[ 74%] Built target pygen_swig_2a55b
[ 88%] Built target _nordic_swig
[ 96%] Built target pygen_python_7499f
[ 96%] Built target pygen_apps_9a6dd
[100%] Built target doxygen_target
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/cmake/nordic/nordicConfig.cmake
-- Installing: /usr/local/include/nordic/api.h
-- Installing: /usr/local/include/nordic/nordic_rx.h
-- Installing: /usr/local/include/nordic/nordic_tx.h
-- Installing: /usr/local/lib/libgnuradio-nordic.dylib
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/_nordic_swig.so
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/nordic_swig.py
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/nordic_swig.pyc
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/nordic_swig.pyo
-- Installing: /usr/local/include/nordic/nordic/swig/nordic_swig.i
-- Installing: /usr/local/include/nordic/nordic/swig/nordic_swig_doc.i
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/__init__.py
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/__init__.pyc
-- Installing: /usr/local/lib/python2.7/site-packages/nordic/__init__.pyo
-- Installing: /usr/local/share/gnuradio/grc/blocks/nordic_nordic_rx.xml
-- Installing: /usr/local/share/gnuradio/grc/blocks/nordic_nordic_tx.xml
-- Up-to-date: /usr/local/share/doc/gr-nordic/xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/api_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/bit__shifting__byte__vector_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classbit__shifting__byte__vector.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classenhanced__shockburst__packet.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classgr_1_1nordic_1_1nordic__rx.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classgr_1_1nordic_1_1nordic__rx__impl.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classgr_1_1nordic_1_1nordic__tx.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/classgr_1_1nordic_1_1nordic__tx__impl.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/combine.xslt
-- Installing: /usr/local/share/doc/gr-nordic/xml/compound.xsd
-- Installing: /usr/local/share/doc/gr-nordic/xml/dir_4d2bec33bd1a813645c7de02e7d2457f.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/dir_97aefd0d527b934f1d99a682da8fe6a9.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/dir_d44c64559bbebec7f509842c48db8b23.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/enhanced__shockburst__packet_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/group__block.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/group__defs_8dox.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/index.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/index.xsd
-- Installing: /usr/local/share/doc/gr-nordic/xml/indexpage.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/main__page_8dox.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/namespacegr.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/namespacegr_1_1nordic.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/namespacestd.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/nordic__rx_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/nordic__rx__impl_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/nordic__tx_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/nordic__tx__impl_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/nordictap_8h.xml
-- Installing: /usr/local/share/doc/gr-nordic/xml/structnordictap__header.xml
-- Up-to-date: /usr/local/share/doc/gr-nordic/html
-- Installing: /usr/local/share/doc/gr-nordic/html/annotated.html
-- Installing: /usr/local/share/doc/gr-nordic/html/annotated_dup.js
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h.js
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__dep__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__dep__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__dep__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/api_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/arrowdown.png
-- Installing: /usr/local/share/doc/gr-nordic/html/arrowright.png
-- Installing: /usr/local/share/doc/gr-nordic/html/bc_s.png
-- Installing: /usr/local/share/doc/gr-nordic/html/bdwn.png
-- Installing: /usr/local/share/doc/gr-nordic/html/bit__shifting__byte__vector_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/bit__shifting__byte__vector_8h__dep__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/bit__shifting__byte__vector_8h__dep__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/bit__shifting__byte__vector_8h__dep__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/bit__shifting__byte__vector_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classbit__shifting__byte__vector-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classbit__shifting__byte__vector.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classbit__shifting__byte__vector.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classenhanced__shockburst__packet-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classenhanced__shockburst__packet.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classenhanced__shockburst__packet.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classes.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl__inherit__graph.map
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl__inherit__graph.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__impl__inherit__graph.png
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__inherit__graph.map
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__inherit__graph.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__rx__inherit__graph.png
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl.html
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl.js
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl__inherit__graph.map
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl__inherit__graph.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__impl__inherit__graph.png
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__inherit__graph.map
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__inherit__graph.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/classgr_1_1nordic_1_1nordic__tx__inherit__graph.png
-- Installing: /usr/local/share/doc/gr-nordic/html/closed.png
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_000002_000000.html
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_4d2bec33bd1a813645c7de02e7d2457f.html
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_4d2bec33bd1a813645c7de02e7d2457f_dep.map
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_4d2bec33bd1a813645c7de02e7d2457f_dep.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_4d2bec33bd1a813645c7de02e7d2457f_dep.png
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_97aefd0d527b934f1d99a682da8fe6a9.html
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.map
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.png
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_d44c64559bbebec7f509842c48db8b23.html
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_d44c64559bbebec7f509842c48db8b23_dep.map
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_d44c64559bbebec7f509842c48db8b23_dep.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/dir_d44c64559bbebec7f509842c48db8b23_dep.png
-- Installing: /usr/local/share/doc/gr-nordic/html/doc.png
-- Installing: /usr/local/share/doc/gr-nordic/html/doxygen.css
-- Installing: /usr/local/share/doc/gr-nordic/html/doxygen.png
-- Installing: /usr/local/share/doc/gr-nordic/html/dynsections.js
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h.js
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__dep__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__dep__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__dep__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/enhanced__shockburst__packet_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/files.html
-- Installing: /usr/local/share/doc/gr-nordic/html/files.js
-- Installing: /usr/local/share/doc/gr-nordic/html/folderclosed.png
-- Installing: /usr/local/share/doc/gr-nordic/html/folderopen.png
-- Installing: /usr/local/share/doc/gr-nordic/html/functions.html
-- Installing: /usr/local/share/doc/gr-nordic/html/functions_func.html
-- Installing: /usr/local/share/doc/gr-nordic/html/functions_type.html
-- Installing: /usr/local/share/doc/gr-nordic/html/functions_vars.html
-- Installing: /usr/local/share/doc/gr-nordic/html/globals.html
-- Installing: /usr/local/share/doc/gr-nordic/html/globals_defs.html
-- Installing: /usr/local/share/doc/gr-nordic/html/globals_func.html
-- Installing: /usr/local/share/doc/gr-nordic/html/globals_vars.html
-- Installing: /usr/local/share/doc/gr-nordic/html/graph_legend.html
-- Installing: /usr/local/share/doc/gr-nordic/html/graph_legend.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/graph_legend.png
-- Installing: /usr/local/share/doc/gr-nordic/html/group__block.html
-- Installing: /usr/local/share/doc/gr-nordic/html/group__defs_8dox.html
-- Installing: /usr/local/share/doc/gr-nordic/html/hierarchy.html
-- Installing: /usr/local/share/doc/gr-nordic/html/hierarchy.js
-- Installing: /usr/local/share/doc/gr-nordic/html/index.html
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_0.map
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_0.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_0.png
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_1.map
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_1.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_1.png
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_2.map
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_2.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_2.png
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_3.map
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_3.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/inherit_graph_3.png
-- Installing: /usr/local/share/doc/gr-nordic/html/inherits.html
-- Installing: /usr/local/share/doc/gr-nordic/html/jquery.js
-- Installing: /usr/local/share/doc/gr-nordic/html/main__page_8dox.html
-- Installing: /usr/local/share/doc/gr-nordic/html/modules.html
-- Installing: /usr/local/share/doc/gr-nordic/html/modules.js
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacegr.html
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacegr.js
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacegr_1_1nordic.html
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacegr_1_1nordic.js
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacemembers.html
-- Installing: /usr/local/share/doc/gr-nordic/html/namespacemembers_vars.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nav_f.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nav_g.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nav_h.png
-- Installing: /usr/local/share/doc/gr-nordic/html/navtree.css
-- Installing: /usr/local/share/doc/gr-nordic/html/navtree.js
-- Installing: /usr/local/share/doc/gr-nordic/html/navtreedata.js
-- Installing: /usr/local/share/doc/gr-nordic/html/navtreeindex0.js
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__dep__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__dep__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__dep__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h.js
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__rx__impl_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__dep__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__dep__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__dep__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx__impl_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx__impl_8h__incl.map
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx__impl_8h__incl.md5
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx__impl_8h__incl.png
-- Installing: /usr/local/share/doc/gr-nordic/html/nordic__tx__impl_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordictap_8h.html
-- Installing: /usr/local/share/doc/gr-nordic/html/nordictap_8h.js
-- Installing: /usr/local/share/doc/gr-nordic/html/nordictap_8h_source.html
-- Installing: /usr/local/share/doc/gr-nordic/html/open.png
-- Installing: /usr/local/share/doc/gr-nordic/html/resize.js
-- Installing: /usr/local/share/doc/gr-nordic/html/splitbar.png
-- Installing: /usr/local/share/doc/gr-nordic/html/structnordictap__header-members.html
-- Installing: /usr/local/share/doc/gr-nordic/html/structnordictap__header.html
-- Installing: /usr/local/share/doc/gr-nordic/html/structnordictap__header.js
-- Installing: /usr/local/share/doc/gr-nordic/html/sync_off.png
-- Installing: /usr/local/share/doc/gr-nordic/html/sync_on.png
-- Installing: /usr/local/share/doc/gr-nordic/html/tab_a.png
-- Installing: /usr/local/share/doc/gr-nordic/html/tab_b.png
-- Installing: /usr/local/share/doc/gr-nordic/html/tab_h.png
-- Installing: /usr/local/share/doc/gr-nordic/html/tab_s.png
-- Installing: /usr/local/share/doc/gr-nordic/html/tabs.css
```

```
./nordic_sniffer_scanner.py 
Traceback (most recent call last):
  File "./nordic_sniffer_scanner.py", line 6, in <module>
    import osmosdr
  File "/usr/local/lib/python2.7/site-packages/osmosdr/__init__.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/local/lib/python2.7/site-packages/osmosdr/osmosdr_swig.py", line 21, in <module>
    _osmosdr_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/osmosdr/osmosdr_swig.py", line 20, in swig_import_helper
    return importlib.import_module('_osmosdr_swig')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _osmosdr_swig
```

```
python nordic_sniffer_scanner.py 
Mac OS; Clang version 7.3.0 (clang-703.0.31); Boost_105900; UHD_003.010.000.000-MacPorts-Release

Traceback (most recent call last):
  File "nordic_sniffer_scanner.py", line 7, in <module>
    import nordic
ImportError: No module named nordic
```

**Comment by marcnewlin** [comment]
I think I see the problem -- it looks like you are missing gr-osmosdr:

```
ImportError: No module named _osmosdr_swig
```

**Comment by cn0xroot** [comment]
gr-osmosdr has ben build:

```

pwd
/Users/Good-Soon/gr-osmosdr/build
SPRITEKING:build Good-Soon$ ls
CMakeCache.txt           cmake_uninstall.cmake    install_manifest.txt
CMakeFiles               docs                     lib
CTestTestfile.cmake      get_swig_deps.py         python
Makefile                 gnuradio-osmosdr.pc      python_compile_helper.py
apps                     grc                      swig
cmake_install.cmake      include
```

**Comment by marcnewlin** [comment]
For a sanity check, what is the output (if any) when you run the following? 

```
python -c 'import osmosdr'
```

**Comment by cn0xroot** [comment]
```
 python -c 'import osmosdr'
Mac OS; Clang version 7.3.0 (clang-703.0.31); Boost_105900; UHD_003.010.000.000-MacPorts-Release

```

**Comment by marcnewlin** [comment]
It looks like a python/swig/environment issue, but I am not familiar enough with OSX to point to anything more specific. 

Do you have an Ubuntu machine/VM you can run it on?

Alternatively, it is possible to install via PyBombs using the [recipe in gr-etcetera](https://github.com/gnuradio/gr-etcetera).

**Comment by cn0xroot** [comment]
i'll try it on ubuntu tomorrow，thanks for you help 😊

**Comment by balint256** [comment]
The `PyThreadState_Get: no current thread` error is caused by linking to the wrong version of Python on your system. Usually it's because you link with the OS X system version of Python, and you need to force it to link to the MacPorts/Homebrew/etc version. You can manually adjust these with `cmake-gui`.

**Comment by cn0xroot** [comment]
i don't konw how to change the link to the right version ?

just like:

`sudo brew unlink swig`?

**Comment by thelumberjhack** [comment]
Hi,

I've got the same issue on my Arch Setup:
```bash
gr-nordic git:(master) python2 ./examples/nordic_sniffer_scanner.py
linux; GNU C++ version 6.2.1 20160830; Boost_106200; UHD_003.009.005-0-unknown

Traceback (most recent call last):
  File "./examples/nordic_sniffer_scanner.py", line 7, in <module>
    import nordic
ImportError: No module named nordic
```

I did not get any problem during setup process so I don't know what I can do to fix that.
Any clue?

Thanks

**Comment by cn0xroot** [comment]
@yformaggio  maybe this is userful to you :)
https://cn0xroot.com/2016/10/08/sniffer-the-nordic-semiconductor-nrf24l-wireless-packet-with-sdr/  

@marcnewlin @balint256 maybe you need add this to your wiki

**Comment by thelumberjhack** [comment]
@cn0xroot thanks, I made a VM with Kali and installed everything except pybombs recipes, and it worked!
