### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nordic_rx'

### ISSUE THREAD

**Issue by moein86** [BastilleResearch/gr-nordic#5]
Running any python example, returns the following error message: 

> linux; GNU C++ version 6.2.0 20161103; Boost_106200; UHD_003.009.005-0-unknown
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya 
Number of USB devices: 7
USB device 1d50:6089: 0000000000000000909864c8335020cf match
Using HackRF One with firmware 2015.07.2 
Traceback (most recent call last):
  File "./nordic_receiver.py", line 134, in <module>
    main()
  File "./nordic_receiver.py", line 123, in main
    tb = top_block(args)
  File "./nordic_receiver.py", line 43, in __init__
    self.rx = nordic.nordic_rx(
AttributeError: 'module' object has no attribute 'nordic_rx'

Do you have any idea that what could have caused that?

**Comment by jfr-shd** [comment]
I am having the same problem....
Did u solve it?
